model:
  _target_: src.modules.models.classification.Classifier
  model_name: "timm/resnet50"
  in_chans: 2
  # checkpoint_path: '/media/images/medical_AI/MAMMO/checkpoints/ssl_postproc_raw_treevias_mammdll_resnet50_best.pth'
  model_repo: null
  pretrained: False
  num_classes: 4
  freeze_layers: null
  # freeze_layers: 8

loss:
  _target_: "torch.nn.CrossEntropyLoss"
  weight: [0.037, 0.076, 0.13, 0.75]

metrics:
  main:
    _target_: torchmetrics.F1Score
    task: multiclass
    num_classes: 4
    top_k: 1
    average: "weighted"  
  valid_best:
    _target_: "torchmetrics.MaxMetric"
  additional:
    AUROC:
      _target_: "torchmetrics.AUROC"
      task: "multiclass"
      num_classes: 4

output_activation:
  _target_: "torch.softmax"
  dim: 1

