model:
  _target_: src.modules.models.classification.Classifier
  model_name: "timm/resnet50"
  in_chans: 2
  model_repo: null
  pretrained: True
  num_classes: 4
  freeze_layers: null

loss:
  _target_: "torch.nn.CrossEntropyLoss"

metrics:
  main:
    _target_: "torchmetrics.Accuracy"
    task: "multiclass"
    num_classes: 4
    top_k: 1
  valid_best:
    _target_: "torchmetrics.MaxMetric"
  additional:
    AUROC:
      _target_: "torchmetrics.AUROC"
      task: "multiclass"
      num_classes: 4

output_activation:
  _target_: "torch.softmax"
  dim: 1

