# this config file is used for running the template default tests

model:
  _target_: src.modules.models.segmentation.Segmentation
  model_name: segmentation_models_pytorch/Unet
#  model_name: custom/Unet
  encoder_name: "mobilenet_v2"
  num_classes: 1
  in_channels: 1
#  classes: 1
#  out_channels: 1
#  features: [4, 8, 16, 32, 64, 128, 256, 512]

loss:
  _target_: "kornia.losses.ssim.SSIMLoss"
  window_size: 21

metrics:
  main: 
    _target_: "torchmetrics.regression.MeanSquaredError"
    # task: "multiclass"
    # num_classes: 1
    # top_k: 1
  valid_best:
    _target_: "torchmetrics.MinMetric"
    

output_activation:
  _target_: "torch.sigmoid"
  # dim: 1
