# this config file is used for running the template default tests

model:
  _target_: src.modules.models.segmentation.Segmentation
  model_name: custom/Unet
  in_channels: 1
  out_channels: 1
  features: [6, 12, 24, 48, 96, 192, 384]

loss:
  _target_: "torch.nn.MSELoss"

metrics:
  main: 
    _target_: "torchmetrics.regression.MeanSquaredError"
    # task: "multiclass"
    # num_classes: 1
    # top_k: 1
  valid_best:
    _target_: "torchmetrics.MinMetric"

output_activation:
  _target_: "torch.sigmoid"
  # dim: 1
