_target_: src.datamodules.bone_shadow_suppression.BonesXRayDataModule

# this config file is used for running the template default tests

datasets:
  # data_path: "/media/images/ОРПО/MEDICINE/JSRT_dataset/archive/JSRT/JSRT"
  # target_path: "/media/images/ОРПО/MEDICINE/JSRT_dataset/archive/BSE_JSRT/BSE_JSRT"
  data_path: "/media/images/ОРПО/MEDICINE/DataSets/JSRT_dataset/archive/JSRT/JSRT_4096_normalized_mixup"
  target_path: "/media/images/ОРПО/MEDICINE/DataSets/JSRT_dataset/archive/BSE_JSRT/BSE_JSRT_4096_normalized_mixup"
  # data_path: "\\\\aserver-images\\images\\ОРПО\\MEDICINE\\DataSets\\JSRT_dataset\\archive\\JSRT\\JSRT_4096_normalized_mixup"
  # target_path: "\\\\aserver-images\\images\\ОРПО\\MEDICINE\\DataSets\\JSRT_dataset\\archive\\BSE_JSRT\\BSE_JSRT_4096_normalized_mixup"
  # data_path: "\\\\aserver-images\\images\\ОРПО\\MEDICINE\\JSRT_dataset\\archive\\JSRT\\JSRT_8bit_mixup"
  # target_path: "\\\\aserver-images\\images\\ОРПО\\MEDICINE\\JSRT_dataset\\archive\\BSE_JSRT\\BSE_JSRT_8bit_mixup"
  # data_path: "\\\\aserver-images\\images\\ОРПО\\MEDICINE\\JSRT_dataset\\archive\\JSRT\\JSRT_8bit"
  # target_path: "\\\\aserver-images\\images\\ОРПО\\MEDICINE\\JSRT_dataset\\archive\\BSE_JSRT\\BSE_JSRT"
  train_val_test_split: [880, 80, 0]
  # train_val_test_split: [220, 20, 0]
  seed: 42

# because we split initial train + test into train + valid + test
transforms:
  train:
    order: ["rotate","resize", "vertical_flip", "horizontal_flip", "normalize", "to_tensor"]
    # order: ["resize", "normalize", "to_tensor"]
    resize:
      _target_: albumentations.Resize
      height: 1536
      width: 1536
      p: 1.0
    random_crop:
      _target_: albumentations.RandomCrop 
      height: 1536
      width: 1536
      p: 1.0
    vertical_flip:
      _target_: albumentations.VerticalFlip
      p: 0.5
    horizontal_flip:
      _target_: albumentations.HorizontalFlip
      p: 0.5
    rotate:
      _target_: albumentations.SafeRotate
      limit: [-30, 30]
      p: 0.5
    normalize:
      _target_: albumentations.Normalize
      mean: [0.0]
      std: [1.0]
      p: 1.0
      max_pixel_value: 65535.0
    to_tensor:
      _target_: albumentations.pytorch.ToTensorV2
      always_apply: True
    additional_targets:
      {'mask': 'image'}

  valid_test_predict:
    order: ["resize", "normalize", "to_tensor"]
    resize:
      _target_: albumentations.Resize
      height: 1536
      width: 1536
      p: 1.0
    normalize:
      _target_: albumentations.Normalize
      mean: [0.0]
      std: [1.0]
      p: 1.0
      max_pixel_value: 65535.0
    to_tensor:
      _target_: albumentations.pytorch.ToTensorV2
      always_apply: True
    additional_targets:
      {'mask': 'image'}

loaders:
  train:
    batch_size: 2
    shuffle: True
    num_workers: 0
    drop_last: True
    pin_memory: False

  valid:
    batch_size: 6
    shuffle: False
    num_workers: 0
    drop_last: False
    pin_memory: False

  test:
    batch_size: 20
    shuffle: False
    num_workers: 0
    drop_last: False
    pin_memory: False

  predict:
    batch_size: 20
    shuffle: False
    num_workers: 0
    drop_last: False
    pin_memory: False